MovieShopMVC/Controllers/CastController.cs
using ApplicationCore.Contracts.Services;
using Microsoft.AspNetCore.Mvc;

namespace MovieShopMVC.Controllers
{
    public class CastController : Controller
    {
        private readonly ICastService _castService;

        public CastController(ICastService castService)
        {
            _castService = castService;
        }

        [HttpGet]
        public async Task<IActionResult> CastDetails(int id)
        {
            var castDetails = await _castService.GetCastDetails(id);
            return View(castDetails);
        }
    }
}

MovieShopMVC/Controllers/MoviesController.cs
using ApplicationCore.Contracts.Repository;
using ApplicationCore.Contracts.Services;
using Microsoft.AspNetCore.Mvc;
using MovieShopMVC.Infra;
using ApplicationCore.Models;

namespace MovieShopMVC.Controllers
{
    public class MoviesController : Controller
    {
        private readonly IMovieService _movieService;
        private readonly IGenreRepository _genreRepository;


        public MoviesController(IMovieService movieService, IGenreRepository genreRepository)
        {
            _movieService = movieService;
            _genreRepository = genreRepository;

        }

        [HttpGet]
        public async Task<IActionResult> Details(int id)
        {
            // go to movie service -> movie repository and get movie details from Movies Table
            var movieDetails = await _movieService.GetMovieDetails(id);
            return View(movieDetails);
        }

        public async Task<ActionResult> GenreMovies(int id, int pageSize = 30, int page = 1)
        {
            var pagedMovies = await _movieService.GetMoviesByPagination(id, pageSize, page);
            ViewData["Title"] = _genreRepository.GetById(id).Result.Name;
            return View(pagedMovies);
        }

    }
}

MovieShopMVC/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using ApplicationCore.Models;
using Microsoft.AspNetCore.Authorization;
using MovieShopMVC.Infra;
using ApplicationCore.Contracts.Services;
using ApplicationCore.Contracts.Repository;

namespace MovieShopMVC.Controllers
{
    [Authorize]
    public class UserController : Controller
    {
        private readonly ICurrentUser _currentUser;
        private readonly IUserService _userService;
        private readonly IMovieService _movieService;
        private readonly IUserRepository _userRepository;


        public UserController(ICurrentUser currentUser, IUserService userService, IMovieService movieService, IUserRepository userRepository)
        {
            _currentUser = currentUser;
            _userService = userService;
            _movieService = movieService;
            _userRepository = userRepository;
        }

        [HttpGet]
        public async Task<IActionResult> Purchases(int pageSize = 30, int page = 1)
        {
            // get all the movies purchased by user , user id
            // httpcontext.user.claims and then call the database and get the information to the view
            if (_currentUser.IsAuthenticated == false)
            {
                return LocalRedirect("~/Account/Login");
            }
            var userId = _currentUser.UserId;
            var pagedMovies = await _userService.GetAllPurchasesForUser(userId, pageSize, page);
            ViewData["Title"] = "Purchases";
            return View(pagedMovies);
        }

        [HttpGet]
        public async Task<IActionResult> PurchaseDetails(int userId, int movieId)
        {
            var purchaseDetails = await _userService.GetPurchasesDetails(userId, movieId);
            return View(purchaseDetails);
        }


        [HttpGet]
        public async Task<IActionResult> Favorites(int pageSize = 30, int page = 1)
        {
            if (_currentUser.IsAuthenticated == false)
            {
                return LocalRedirect("~/Account/Login");
            }
            var userId = _currentUser.UserId;
            var pagedMovies = await _userService.GetAllFavoritesForUser(userId, pageSize, page);
            ViewData["Title"] = "Favorites";
            return View(pagedMovies);
        }

        [HttpGet]
        public async Task<IActionResult> EditProfile()
        {

            if (_currentUser.IsAuthenticated == false)
            {
                return LocalRedirect("~/Account/Login");
            }

            var getPro = await _userRepository.GetById(_currentUser.UserId);
            UserEditModel editPro = new UserEditModel
            {
                FirstName = getPro.FirstName,
                LastName = getPro.LastName,
                Email = getPro.Email,
                DateOfBirth = (DateTime)getPro.DateOfBirth
            };


            return View(editPro);
        }

        [HttpPost]
        public async Task<IActionResult> EditProfile(UserEditModel model)
        {

            if (_currentUser.IsAuthenticated == false)
            {
                return LocalRedirect("~/Account/Login");
            }
            UserEditModel editPro = new UserEditModel
            {
                FirstName = model.FirstName,
                LastName = model.LastName,
                Email = model.Email,
                Password = model.Password,
                DateOfBirth = model.DateOfBirth
            };

            var profileUpdateSuccess = await _userService.EditProfile(editPro, _currentUser.UserId);

            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        public IActionResult BuyMovie(int movieId)
        {
            if (_currentUser.IsAuthenticated == false)
            {
                return LocalRedirect("~/Account/Login");
            }
            return RedirectToAction("Details", "Movies", new { id = movieId });
        }


        [HttpPost]
        public async Task<IActionResult> BuyMovie(int movieId, int userId)
        {
            if (_currentUser.IsAuthenticated == false)
            {
                return LocalRedirect("~/Account/Login");
            }

            UserPurchaseRequestModel purchase = new UserPurchaseRequestModel
            {
                UserId = _currentUser.UserId,
                MovieId = movieId
            };
            var purchaseSuccess = await _userService.PurchaseMovie(purchase, _currentUser.UserId);
            return RedirectToAction("Details", "Movies", new { id = movieId });
        }

        [HttpGet]
        public IActionResult FavoriteMovie(int movieId)
        {
            if (_currentUser.IsAuthenticated == false)
            {
                return LocalRedirect("~/Account/Login");
            }
            return RedirectToAction("Details", "Movies", new { id = movieId });
        }

        [HttpPost]
        public async Task<IActionResult> FavoriteMovie(int movieId, int userId, int actionId)
        {
            if (_currentUser.IsAuthenticated == false)
            {
                return LocalRedirect("~/Account/Login");
            }

            if (actionId == 1)
            {
                UserFavoriteRequestModel favorite = new UserFavoriteRequestModel
                {
                    UserId = _currentUser.UserId,
                    MovieId = movieId
                };
                var favoriteAddSuccess = await _userService.AddFavorite(favorite);
            }
            else if (actionId == 0)
            {
                UserFavoriteRequestModel favorite = new UserFavoriteRequestModel
                {
                    UserId = _currentUser.UserId,
                    MovieId = movieId
                };

                var favoriteRemoveSuccess = await _userService.RemoveFavorite(favorite);
            }

            return RedirectToAction("Details", "Movies", new { id = movieId });
        }
        [HttpGet]
        public IActionResult ReviewMovie(int movieId)
        {
            
            if (_currentUser.IsAuthenticated == false)
            {
                return LocalRedirect("~/Account/Login");
            }
            //return RedirectToAction("Details", "Movies", new { id = movieId });
            ViewData["Title"] = "Review" + _movieService.GetMovieDetails(movieId).Result.Title;
            ReviewDetailsModel review = new ReviewDetailsModel
            {
                MovieId = movieId,
                UserId = _currentUser.UserId
            };
            if (_userService.ReviewExists(_currentUser.UserId, movieId).Result)
            {
                review = _userService.GetReviewDetails(_currentUser.UserId, movieId).Result;
            }
          
            return View(review);
        }


        [HttpPost]
        public async Task<IActionResult> ReviewMovie(UserReviewRequestModel model,int movieId ,int actionId)
        {
            if (_currentUser.IsAuthenticated == false)
            {
                return LocalRedirect("~/Account/Login");
            }
            UserReviewRequestModel review = new UserReviewRequestModel
            {
                MovieId = movieId,
                UserId = _currentUser.UserId,
                Rating = model.Rating,
                ReviewText = model.ReviewText
            };
            

            if (actionId == 1)
            {
                if (await _userService.ReviewExists(_currentUser.UserId, review.MovieId))
                {
                    var reviewUpdateSuccess = await _userService.UpdateMovieReview(review);
                }
                else
                {
                    var reviewAddSuccess = await _userService.AddMovieReview(review);
                }

            }
            else if (actionId == 0)
            {

                var reviewDeleteSuccess = await _userService.DeleteMovieReview(_currentUser.UserId, review.MovieId);
            }



            return RedirectToAction("Details", "Movies", new { id = review.MovieId });
        }
    }
}

MovieShopMVC/Views/Movies/Details.cshtml
@model ApplicationCore.Models.MovieDetailsModel
@using MovieShopMVC.Infra
@inject ICurrentUser currentUser
@using ApplicationCore.Contracts.Services
@inject IUserService userService
@using System;

@{
	ViewData["Title"] = @Model.Title;
}

<div class="container-fluid">
	<div class="row">
		<div class="bg-image" style="background-image: url('@Model.BackdropUrl'); background-position:center; background-size:cover; background-repeat:no-repeat; height:50vh">
			<div class="mask" style="background-color: rgba(0, 0, 0, 0.6); height:50vh">
				<div class="row">
					<div class="col-3 text-end">
						<img src="@Model.PosterUrl" style="height:50vh" />
					</div>
					<div class="col-5 offset-1">
						<h2 class="text-white">@Model.Title</h2>
						<p style="color:lightgray">@Model.Tagline</p>
						<h6>
							<span style="color:lightgray">@Model.RunTime m | @Model.ReleaseDate.Value.Year</span>
							<span style="float:right">
								@foreach (var g in Model.Genres)
								{
									<span><p class="badge bg-secondary rounded-pill">@g.Name</p></span>
								}
							</span>
						</h6>
						<h1 class="badge bg-success" style="font-size:1em">@String.Format("{0:0.00}", @Model.Rating)</h1>
						<p class="text-white">@Model.Overview</p>
					</div>
					<div class="col-3 pt-5 text-end">
						<div class="pb-3">
							@*
							<button type="button" class="btn btn-outline-light" style="width:60%" data-bs-toggle="modal" data-bs-target="#ReviewModal"><i class="bi bi-pencil-square"></i> REVIEW</button>
							*@
							<a asp-controller="User" asp-action="ReviewMovie" asp-route-movieId="@Model.Id">
								<button type="button" class="btn btn-outline-light" style="width:60%"><i class="bi bi-pencil-square"></i> REVIEW</button>
							</a>

						</div>
						<div class="pb-3">
							@if (currentUser.IsAuthenticated)
							{
								@if (await userService.IsMoviePurchased(currentUser.UserId, Model.Id))
								{
									<a href="@Model.TmdbUrl" target="_blank"><button type="button" class="btn btn-light" style="width:60%">WATCH MOVIE</button></a>
								}
								else
								{
									<button type="button" class="btn btn-light" style="width:60%" data-bs-toggle="modal" data-bs-target="#BuyModal">BUY $@Model.Price</button>
								}
							}
							else
							{
								<button type="button" class="btn btn-light" style="width:60%" data-bs-toggle="modal" data-bs-target="#BuyModal">BUY $@Model.Price</button>
							}
						</div>
						<div>
							@if (currentUser.IsAuthenticated)
							{
								@if (await userService.FavoriteExists(currentUser.UserId, Model.Id))
								{
									<form asp-controller="User" asp-action="FavoriteMovie" asp-route-movieId="@Model.Id" asp-route-actionId="0">
										<button type="submit" class="btn btn-danger" style="width:60%">FAVORITE <i class="bi bi-heart"></i></button>
									</form>
								}
								else
								{
									<form asp-controller="User" asp-action="FavoriteMovie" asp-route-movieId="@Model.Id" asp-route-actionId="1">
										<button type="submit" class="btn btn-outline-danger" style="width:60%">FAVORITE <i class="bi bi-heart"></i></button>
									</form>
								}
							}
							else
							{
								<a asp-controller="Account" asp-action="Login">
									<button type="button" class="btn btn-outline-danger" style="width:60%">FAVORITE <i class="bi bi-heart"></i></button>
								</a>
							}

						</div>
					</div>
				</div>
				<div class="row mt-3">
					<div class="col-3" style="background-color:whitesmoke">
						<div class="mb-3">
							<p2>MOVIE FACTS</p2>
							<hr />
							<ul class="list-group list-group-flush mt-2">
								<li class="list-group-item" style="background-color:whitesmoke">
									<i class="bi bi-calendar-week"></i> Release Date
									<span class="badge rounded-pill bg-dark">@Model.ReleaseDate.Value.Date.ToString("d")</span>
								</li>
								<li class="list-group-item" style="background-color:whitesmoke">
									<i class="bi bi-hourglass-split"></i> Run Time
									<span class="badge rounded-pill bg-dark">@Model.RunTime m</span>
								</li>
								<li class="list-group-item" style="background-color:whitesmoke">
									<i class="bi bi-cash"></i> Box Office
									<span class="badge rounded-pill bg-dark">@string.Format("{0:C}",@Model.Revenue)</span>
								</li>
								<li class="list-group-item" style="background-color:whitesmoke">
									<i class="bi bi-currency-dollar"></i> Budget
									<span class="badge rounded-pill bg-dark">@string.Format("{0:C}",@Model.Budget)</span>
								</li>
								<li class="list-group-item" style="background-color:whitesmoke">
									<a href="@Model.ImdbUrl" target="_blank"><i class="fa-brands fa-imdb"></i></a>
									<i class="fa-solid fa-share-from-square"></i>
								</li>
							</ul>
						</div>
						<div>
							<p2 class="pt-4">TRAILERS</p2>
							<hr />
							<ul class="list-group list-group-flush mt-2">
								@foreach (var t in @Model.Trailers)
								{
									<li class="list-group-item" style="background-color:whitesmoke">
										<i class="bi bi-youtube"></i>
										<a href="@t.TrailerUrl" target="_blank" class="text-black text-decoration-none">@t.Name</a>
									</li>
								}
							</ul>
						</div>
					</div>
					<div class="col-7 offset-1">
						<p2>CAST</p2>
						<hr />
						<ul class="list-group list-group-flush mt-2">
							@foreach (var c in @Model.Casts)
							{
								<li class="list-group-item">
									<div style="float:left; width:10%">
										<a asp-controller="Cast" asp-action="CastDetails" asp-route-id="@c.Id">
											<img src="@c.ProfilePath" alt="@c.Name" class="rounded-circle" style="width:50%">
										</a>
									</div>
									<div style="float:left; width:50%">
										@c.Name
									</div>
									<div style="float:left; width:40%">
										@c.Character
									</div>
								</li>
							}
						</ul>
					</div>
				</div>
			</div>
		</div>

	</div>

</div>

<div class="modal fade" id="BuyModal" tabindex="-1" aria-labelledby="BuyModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title" id="BuyModalLabel">Confirmation</h5>
				<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
			</div>
			<div class="modal-body">
				<h3>@Model.Title</h3>
				<h4>Price: $@Model.Price</h4>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
				<form asp-controller="User" asp-action="BuyMovie" asp-route-movieId="@Model.Id">
					<button type="submit" class="btn btn-primary">Purchase</button>
				</form>
			</div>
		</div>
	</div>
</div>
@*
<div class="modal fade" id="ReviewModal" tabindex="-1" aria-labelledby="ReviewModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title" id="ReviewModalLabel">Review</h5>
				<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
			</div>
				<div class="modal-body">
					<select class="form-select" aria-label="Rating" id="ReviewRating">
						<option selected>Rating</option>
						<option value="1">1</option>
						<option value="2">2</option>
						<option value="3">3</option>
						<option value="4">4</option>
						<option value="5">5</option>
						<option value="6">6</option>
						<option value="7">7</option>
						<option value="8">8</option>
						<option value="9">9</option>
						<option value="10">10</option>
					</select>
					<hr />
					<div class="form-floating">
						<textarea class="form-control" placeholder="Leave a review here" id="floatingTextareaReview"></textarea>
						<label for="floatingTextareaReview">Review</label>
					</div>
				</div>
				<div class="modal-footer">
					<button type="submit" class="btn btn-danger" asp-route-actionId="0">Delete</button>
					<button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
					<button type="submit" class="btn btn-primary" asp-route-actionId="1">Submit</button>
				</div>
		</div>
	</div>
</div>
*@

@section Scripts {
	@{
		await Html.RenderPartialAsync("_ValidationScriptsPartial");
	}
	}

MovieShopMVC/Views/Movies/GenreMovies.cshtml
@using ApplicationCore.Models
@model PagedResultSet<MovieCardModel>


<div class="rounded">
	<div class="container-fluid">
		<div class="row">
			@foreach (var movieCard in Model?.Data)
			{
				<div class="col-xl-2 col-sm-4 col-lg-3 col-6">

					<partial name="_MovieCard" model="@movieCard" />
				</div>
			}
		</div>
	</div>
</div>

@{
	var firstDisabled = !Model.HasPreviousPage ? "disabled" : "";
	var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
	var nextDisabled = !Model.HasNextPage ? "disabled" : "";
	var lastDisabled = !Model.HasNextPage ? "disabled" : "";
}
<div class="mt-5">

	<a asp-action="GenreMovies" asp-route-page="1" class="btn btn-outline-primary @firstDisabled"> << </a>
	<a asp-action="GenreMovies" asp-route-page="@(Model.PageIndex-1)" class="btn btn-outline-primary @prevDisabled"> < </a>


	@if (Model.TotalPages <= 5)
	{
		@for (var i = 1; i <= Model.TotalPages; i++)
		{
			@if (i == Model.PageIndex)
			{
				<a asp-action="GenreMovies" asp-route-page="@i" class="btn btn-outline-primary active"> @i </a>
			}
			else
			{
				<a asp-action="GenreMovies" asp-route-page="@i" class="btn btn-outline-primary"> @i </a>
			}
		}
	}
	else if (Model.PageIndex <= 3)
	{
		@for (var i = 1; i <= 5; i++)
		{
			@if (i == Model.PageIndex)
			{
				<a asp-action="GenreMovies" asp-route-page="@i" class="btn btn-outline-primary active"> @i </a>
			}
			else
			{
				<a asp-action="GenreMovies" asp-route-page="@i" class="btn btn-outline-primary"> @i </a>
			}
		}
		<a class="btn btn-outline-primary disabled"> ... </a>
	}
	else if (Model.PageIndex >= (Model.TotalPages - 2))
	{
		<a class="btn btn-outline-primary disabled"> ... </a>
		@for (var i = Model.TotalPages - 4; i <= Model.TotalPages; i++)
		{
			@if (i == Model.PageIndex)
			{
				<a asp-action="GenreMovies" asp-route-page="@i" class="btn btn-outline-primary active"> @i </a>
			}
			else
			{
				<a asp-action="GenreMovies" asp-route-page="@i" class="btn btn-outline-primary"> @i </a>
			}
		}
	}
	else
	{
		<a class="btn btn-outline-primary disabled"> ... </a>
		@for (var i = Model.PageIndex - 2; i <= Model.PageIndex + 2; i++)
		{
			@if (i == Model.PageIndex)
			{
				<a asp-action="GenreMovies" asp-route-page="@i" class="btn btn-outline-primary active"> @i </a>
			}
			else
			{
				<a asp-action="GenreMovies" asp-route-page="@i" class="btn btn-outline-primary"> @i </a>
			}
		}
		<a class="btn btn-outline-primary disabled"> ... </a>
	}

	<a asp-action="GenreMovies" asp-route-page="@(Model.PageIndex+1)" class="btn btn-outline-primary @nextDisabled"> > </a>
	<a asp-action="GenreMovies" asp-route-page="@(Model.TotalPages)" class="btn btn-outline-primary @lastDisabled"> >> </a>

</div>